controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

groupe_testeurs_add:
    path: /groupeTesteurs
    controller: 'App\Controller\GroupeTesteursController::createGroupeTesteurs'
    methods: ['POST']
